import os
import shutil
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    roc_curve,
    precision_recall_curve,
    confusion_matrix,
)
from typing import Dict, Any, Tuple, List
from src.utils import save_json, save_config, compute_sha256, get_metadata, load_json
from src.data import create_dataset


def compute_metrics_at_threshold(
    y_true: np.ndarray,
    y_prob: np.ndarray,
    threshold: float = 0.5,
) -> Dict[str, Any]:
    """
    Compute comprehensive binary classification metrics per Section 8.1.
    """
    y_pred = (y_prob >= threshold).astype(int)
    
    # Safe AUC computations
    try:
        roc_auc = float(roc_auc_score(y_true, y_prob))
    except Exception:
        roc_auc = float("nan")

    try:
        pr_auc = float(average_precision_score(y_true, y_prob))
    except Exception:
        pr_auc = float("nan")

    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = int(cm[0, 0]), int(cm[0, 1]), int(cm[1, 0]), int(cm[1, 1])

    sensitivity = float(tp / (tp + fn)) if (tp + fn) > 0 else 0.0
    specificity = float(tn / (tn + fp)) if (tn + fp) > 0 else 0.0
    precision = float(tp / (tp + fp)) if (tp + fp) > 0 else 0.0
    f1 = float(2 * precision * sensitivity / (precision + sensitivity)) if (precision + sensitivity) > 0 else 0.0
    balanced_accuracy = float((sensitivity + specificity) / 2.0)

    return {
        "threshold": float(threshold),
        "roc_auc": roc_auc,
        "pr_auc": pr_auc,
        "sensitivity_recall": sensitivity,
        "specificity": specificity,
        "precision": precision,
        "f1_score": f1,
        "balanced_accuracy": balanced_accuracy,
        "confusion_matrix": {
            "tn": tn,
            "fp": fp,
            "fn": fn,
            "tp": tp,
        },
    }


def find_youden_j_threshold(y_true: np.ndarray, y_prob: np.ndarray) -> Tuple[float, float]:
    """
    Determine threshold maximizing Youden's J = sensitivity + specificity - 1 per Section 8.2.
    """
    fpr, tpr, thresholds = roc_curve(y_true, y_prob)
    # Youden's J = tpr - fpr = sensitivity + specificity - 1
    j_scores = tpr - fpr
    best_idx = int(np.argmax(j_scores))
    
    best_threshold = float(thresholds[best_idx])
    # Handle infinite threshold boundary if generated by sklearn
    if np.isinf(best_threshold) or best_threshold > 1.0:
        best_threshold = 1.0
    elif best_threshold < 0.0:
        best_threshold = 0.0
        
    best_j = float(j_scores[best_idx])
    return best_threshold, best_j


def plot_roc_curve(y_true: np.ndarray, y_prob: np.ndarray, save_path: str) -> None:
    """Plot and save ROC curve."""
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    auc_val = roc_auc_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else 0.5

    plt.figure(figsize=(6, 5))
    plt.plot(fpr, tpr, color="#1f77b4", lw=2, label=f"ROC Curve (AUC = {auc_val:.4f})")
    plt.plot([0, 1], [0, 1], color="#7f7f7f", linestyle="--", lw=1.5, label="Chance")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("False Positive Rate (1 - Specificity)")
    plt.ylabel("True Positive Rate (Sensitivity)")
    plt.title("Receiver Operating Characteristic (ROC)")
    plt.legend(loc="lower right")
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_pr_curve(y_true: np.ndarray, y_prob: np.ndarray, save_path: str) -> None:
    """Plot and save Precision-Recall curve."""
    precision, recall, _ = precision_recall_curve(y_true, y_prob)
    pr_auc_val = average_precision_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else 0.5

    plt.figure(figsize=(6, 5))
    plt.plot(recall, precision, color="#2ca02c", lw=2, label=f"PR Curve (AUC = {pr_auc_val:.4f})")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel("Recall (Sensitivity)")
    plt.ylabel("Precision")
    plt.title("Precision-Recall Curve")
    plt.legend(loc="lower left")
    plt.grid(True, linestyle=":", alpha=0.6)
    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_confusion_matrix_heatmap(
    cm_dict: Dict[str, int],
    class_names: List[str],
    save_path: str,
    title: str = "Confusion Matrix",
) -> None:
    """Plot and save Confusion Matrix heatmap."""
    cm_array = np.array([
        [cm_dict["tn"], cm_dict["fp"]],
        [cm_dict["fn"], cm_dict["tp"]],
    ])
    plt.figure(figsize=(5, 4))
    sns.heatmap(
        cm_array,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=class_names,
        yticklabels=class_names,
    )
    plt.xlabel("Predicted Class")
    plt.ylabel("True Class")
    plt.title(title)
    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_cv_learning_curves(run_dir: str, n_folds: int, save_path: str) -> None:
    """Plot and save loss and accuracy across all CV folds."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    for fold in range(n_folds):
        hist_path = os.path.join(run_dir, f"fold_{fold}", "history.csv")
        if os.path.exists(hist_path):
            df = pd.read_csv(hist_path)
            epochs = df["epoch"] if "epoch" in df.columns else range(1, len(df) + 1)
            
            axes[0].plot(epochs, df["loss"], linestyle="--", alpha=0.6, label=f"F{fold} Train")
            axes[0].plot(epochs, df["val_loss"], linestyle="-", label=f"F{fold} Val")
            
            acc_col = "accuracy" if "accuracy" in df.columns else ("acc" if "acc" in df.columns else None)
            val_acc_col = "val_accuracy" if "val_accuracy" in df.columns else ("val_acc" if "val_acc" in df.columns else None)
            if acc_col and val_acc_col:
                axes[1].plot(epochs, df[acc_col], linestyle="--", alpha=0.6, label=f"F{fold} Train")
                axes[1].plot(epochs, df[val_acc_col], linestyle="-", label=f"F{fold} Val")

    axes[0].set_title("Cross-Entropy Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].grid(visible=True, linestyle=":", alpha=0.6)
    handles0, _ = axes[0].get_legend_handles_labels()
    if handles0:
        axes[0].legend()

    axes[1].set_title("Accuracy")
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].grid(visible=True, linestyle=":", alpha=0.6)
    handles1, _ = axes[1].get_legend_handles_labels()
    if handles1:
        axes[1].legend()

    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=300)
    plt.close()


def evaluate_oof_and_select_threshold(run_dir: str, config: Dict[str, Any], n_folds: int = 5) -> Dict[str, Any]:
    """
    Concatenate 5 validation folds, select Youden's J threshold, and save OOF artifacts.
    """
    oof_dfs = []
    best_epochs = []

    for fold in range(n_folds):
        pred_path = os.path.join(run_dir, f"fold_{fold}", "val_predictions.csv")
        metrics_path = os.path.join(run_dir, f"fold_{fold}", "fold_metrics.json")
        
        if not os.path.exists(pred_path):
            raise FileNotFoundError(f"Missing fold {fold} predictions at {pred_path}")
        
        oof_dfs.append(pd.read_csv(pred_path))
        if os.path.exists(metrics_path):
            f_metrics = load_json(metrics_path)
            if "best_epoch" not in f_metrics or not isinstance(f_metrics["best_epoch"], (int, float)) or f_metrics["best_epoch"] < 1:
                raise ValueError(f"Integrity Error: fold_metrics.json at '{metrics_path}' is missing a valid 'best_epoch' field.")
            best_epochs.append(int(f_metrics["best_epoch"]))

    pooled_oof_df = pd.concat(oof_dfs, ignore_index=True)
    oof_csv_path = os.path.join(run_dir, "oof_predictions.csv")
    pooled_oof_df.to_csv(oof_csv_path, index=False)

    y_true = pooled_oof_df["y_true"].values
    y_prob = pooled_oof_df["stone_probability"].values

    # Determine Youden J threshold
    best_thresh, best_j = find_youden_j_threshold(y_true, y_prob)

    # Compute metrics at locked threshold and 0.5 reference
    locked_metrics = compute_metrics_at_threshold(y_true, y_prob, threshold=best_thresh)
    ref_0_5_metrics = compute_metrics_at_threshold(y_true, y_prob, threshold=0.5)

    threshold_info = {
        "strategy": "youden_j_oof",
        "threshold": best_thresh,
        "youden_j": best_j,
        "reference_0_5_metrics": ref_0_5_metrics,
    }
    save_json(threshold_info, os.path.join(run_dir, "threshold.json"))

    oof_results = {
        "total_oof_samples": len(pooled_oof_df),
        "locked_threshold_metrics": locked_metrics,
        "best_epochs_per_fold": best_epochs,
        "median_best_epoch": int(round(float(np.median(best_epochs)))) if best_epochs else 1,
    }
    save_json(oof_results, os.path.join(run_dir, "oof_metrics.json"))

    # Generate Plots
    plots_dir = os.path.join(run_dir, "plots")
    class_names = config.get("evaluation", {}).get("class_names", ["Non-Stone", "Stone"])
    plot_roc_curve(y_true, y_prob, os.path.join(plots_dir, "roc_curve.png"))
    plot_pr_curve(y_true, y_prob, os.path.join(plots_dir, "pr_curve.png"))
    plot_confusion_matrix_heatmap(
        locked_metrics["confusion_matrix"],
        class_names=class_names,
        save_path=os.path.join(plots_dir, "confusion_matrix.png"),
        title=f"OOF Confusion Matrix (Threshold={best_thresh:.4f})",
    )
    plot_cv_learning_curves(run_dir, n_folds=n_folds, save_path=os.path.join(plots_dir, "learning_curves.png"))

    return oof_results


def evaluate_sealed_test_set(
    test_manifest_df: pd.DataFrame,
    data_dir: str,
    model_path: str,
    locked_threshold: float,
    run_dir: str,
    config: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Evaluate once on the sealed 40-patient test set per Section 8.4:
      - Uses original images only.
      - Predicts once with final trained model.
      - Saves test_predictions.csv before metrics calculation.
      - Computes all metrics using locked threshold.
    """
    final_dir = os.path.join(run_dir, "final")
    os.makedirs(final_dir, exist_ok=True)

    # Filter original test images
    test_df = test_manifest_df[
        (test_manifest_df["split"] == "test") & (test_manifest_df["is_original"] == True)
    ].copy().reset_index(drop=True)

    test_ds = create_dataset(test_df, data_dir, config, split_type="test")
    model = tf.keras.models.load_model(model_path)

    # 1. Predict and save raw probabilities
    raw_preds = model.predict(test_ds, verbose=0)
    stone_probs = raw_preds[:, 1]
    y_true = test_df["label"].astype(int).values

    test_pred_df = pd.DataFrame({
        "path": test_df["path"],
        "patient_id": test_df["patient_id"],
        "source_image_id": test_df["source_image_id"],
        "y_true": y_true,
        "stone_probability": stone_probs,
        "predicted_class": (stone_probs >= locked_threshold).astype(int),
    })
    test_pred_csv = os.path.join(final_dir, "test_predictions.csv")
    test_pred_df.to_csv(test_pred_csv, index=False)

    # 2. Compute test metrics at locked threshold
    test_metrics = compute_metrics_at_threshold(y_true, stone_probs, threshold=locked_threshold)
    save_json(test_metrics, os.path.join(final_dir, "test_metrics.json"))

    # 3. Generate test plots
    test_plots_dir = os.path.join(final_dir, "plots")
    class_names = config.get("evaluation", {}).get("class_names", ["Non-Stone", "Stone"])
    plot_roc_curve(y_true, stone_probs, os.path.join(test_plots_dir, "test_roc_curve.png"))
    plot_pr_curve(y_true, stone_probs, os.path.join(test_plots_dir, "test_pr_curve.png"))
    plot_confusion_matrix_heatmap(
        test_metrics["confusion_matrix"],
        class_names=class_names,
        save_path=os.path.join(test_plots_dir, "test_confusion_matrix.png"),
        title=f"Final Test Confusion Matrix (Threshold={locked_threshold:.4f})",
    )

    return test_metrics


def export_inference_bundle(
    run_dir: str,
    final_model_path: str,
    locked_threshold: float,
    config: Dict[str, Any],
    metadata: Dict[str, Any],
) -> str:
    """
    Export inference bundle per Section 10.1:
      runs/<run_id>/final/bundle/
        ├── model.keras
        ├── inference_config.json
        └── provenance.json
    """
    bundle_dir = os.path.join(run_dir, "final", "bundle")
    os.makedirs(bundle_dir, exist_ok=True)

    # 1. Copy model.keras
    bundle_model_path = os.path.join(bundle_dir, "model.keras")
    shutil.copyfile(final_model_path, bundle_model_path)

    # 2. Write inference_config.json matching spec Section 10.1
    inference_config = {
        "image_size": config.get("data", {}).get("image_size", 384),
        "channels": config.get("data", {}).get("channels", 1),
        "resize": "resize_with_pad",
        "scale": "0_1",
        "class_names": config.get("evaluation", {}).get("class_names", ["Non-Stone", "Stone"]),
        "stone_class_index": 1,
        "threshold": locked_threshold,
    }
    save_json(inference_config, os.path.join(bundle_dir, "inference_config.json"))

    # 3. Write provenance.json
    provenance = {
        "run_id": metadata.get("run_id"),
        "timestamp": metadata.get("timestamp"),
        "git_commit": metadata.get("git_commit"),
        "dataset_manifest_hash": metadata.get("dataset_manifest_hash"),
        "outer_split_hash": metadata.get("outer_split_hash"),
        "cv_fold_hash": metadata.get("cv_fold_hash"),
        "model_sha256": compute_sha256(bundle_model_path),
        "locked_threshold": locked_threshold,
    }
    save_json(provenance, os.path.join(bundle_dir, "provenance.json"))

    print(f"Inference bundle successfully exported to: {bundle_dir}")
    return bundle_dir
